# Generated by Django 4.2.4 on 2023-08-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Short name', models.CharField(max_length=20)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
